// ============================================================
// LEARN FORGE — Shared Project Database (36 projects)
// Loaded as a plain <script> tag — sets window.LF_PROJECTS
// ============================================================
(function () {
  window.LF_PROJECTS = [

    // ── WEB ──────────────────────────────────────────────────

    {
      id: 'web-weather-dashboard', category: 'web', difficulty: 'easy', featured: true,
      title: 'Weather Dashboard App',
      desc: 'Build a beautiful weather dashboard showing current conditions and a 7-day forecast for any city using the OpenWeatherMap API.',
      longDesc: 'Create a fully functional weather application that lets users search any city worldwide and view detailed weather info including temperature, humidity, wind speed, UV index, and a 7-day forecast. Practice REST APIs, async JavaScript, and creating data visualisations.',
      tech: ['javascript', 'html-css'],
      tags: ['OpenWeather API', 'REST', 'CSS', 'Geolocation'],
      skills: ['API Integration', 'Async/Await', 'Data Rendering', 'Responsive Design'],
      requirements: [
        'Search for any city by name using the OpenWeatherMap API',
        'Display temperature (°C/°F toggle), humidity, wind speed, and UV index',
        'Show a 5-day forecast with weather icons and descriptions',
        'Auto-detect the user\'s city using the Geolocation API',
        'Save and display recent searches using localStorage',
        'Fully responsive layout that looks great on mobile',
      ],
      resources: [
        { label: 'OpenWeatherMap Free API', url: 'https://openweathermap.org/api' },
        { label: 'MDN Fetch API', url: 'https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API' },
        { label: 'Geolocation API', url: 'https://developer.mozilla.org/en-US/docs/Web/API/Geolocation_API' },
      ],
      devs: 4821, time: '3–5 days',
    },

    {
      id: 'web-url-shortener', category: 'web', difficulty: 'medium', featured: false,
      title: 'URL Shortener with Analytics',
      desc: 'Build a full-stack URL shortener with click tracking, analytics dashboard, and custom aliases — similar to Bitly.',
      longDesc: 'Design and build a complete URL shortening service with a Node.js/Express backend, MongoDB database, and a clean frontend dashboard. Track clicks, referrers, and geographic data. Learn about hashing, redirects, and building RESTful APIs.',
      tech: ['javascript', 'node', 'html-css'],
      tags: ['Node.js', 'Express', 'MongoDB', 'REST API'],
      skills: ['REST API Design', 'Database Modeling', 'URL Hashing', 'Analytics'],
      requirements: [
        'Accept a long URL and generate a unique short code',
        'Redirect users from short URL to the original URL',
        'Track total clicks, unique visitors, and referrer data',
        'Allow custom aliases (e.g. learnforge.dev/my-link)',
        'Build a dashboard showing click analytics with charts',
        'Add an expiry date option for temporary short links',
      ],
      resources: [
        { label: 'Express.js Docs', url: 'https://expressjs.com' },
        { label: 'MongoDB Atlas Free Tier', url: 'https://www.mongodb.com/cloud/atlas' },
        { label: 'nanoid (ID generator)', url: 'https://github.com/ai/nanoid' },
      ],
      devs: 1240, time: '1–2 weeks',
    },

    {
      id: 'web-recipe-finder', category: 'web', difficulty: 'easy', featured: false,
      title: 'Recipe Finder App',
      desc: 'Search thousands of recipes by ingredient, cuisine, or diet using the Spoonacular or Edamam API and display them in a mouth-watering UI.',
      longDesc: 'Build a recipe discovery application where users can search by ingredient (e.g. "chicken, garlic"), filter by diet type (vegan, keto, gluten-free), and browse cuisine categories. Save favourites locally. Great for practising API calls, search filtering, and card-based layouts.',
      tech: ['javascript', 'react', 'html-css'],
      tags: ['Spoonacular API', 'React', 'LocalStorage', 'Filtering'],
      skills: ['API Integration', 'Search & Filter', 'Component Design', 'State Management'],
      requirements: [
        'Search recipes by keyword, ingredient, or cuisine type',
        'Filter by diet (vegetarian, vegan, gluten-free, keto)',
        'Display recipe cards with image, title, cook time, and rating',
        'Open a detail view with full ingredients and step-by-step instructions',
        'Save favourite recipes to localStorage',
        'Pagination or infinite scroll for search results',
      ],
      resources: [
        { label: 'Spoonacular API Docs', url: 'https://spoonacular.com/food-api' },
        { label: 'Edamam Recipe API', url: 'https://developer.edamam.com' },
      ],
      devs: 3100, time: '3–5 days',
    },

    {
      id: 'web-movie-db', category: 'web', difficulty: 'medium', featured: true,
      title: 'Movie Database Browser',
      desc: 'Build a Netflix-style movie browser backed by the TMDB API — search, discover trending films, view trailers, and save watchlists.',
      longDesc: 'Create a polished movie discovery app using The Movie Database (TMDB) API. Display trending movies, allow searching by title or genre, view full details, watch YouTube trailers, and manage a personal watchlist. This is a great project for mastering API pagination, lazy loading images, and responsive grid layouts.',
      tech: ['react', 'javascript', 'html-css'],
      tags: ['TMDB API', 'React', 'Responsive Grid', 'YouTube Embed'],
      skills: ['API Pagination', 'Image Lazy Loading', 'State Management', 'Routing'],
      requirements: [
        'Display trending and popular movies on the homepage',
        'Search movies by title with real-time results',
        'Show a detailed page per movie: synopsis, cast, rating, runtime',
        'Embed a YouTube trailer for each movie',
        'Filter movies by genre using TMDB discover endpoint',
        'Add movies to a local watchlist stored in localStorage',
      ],
      resources: [
        { label: 'TMDB API Docs', url: 'https://developers.themoviedb.org/3' },
        { label: 'React Router v6 Docs', url: 'https://reactrouter.com/en/main' },
      ],
      devs: 2750, time: '1–2 weeks',
    },

    {
      id: 'web-kanban-board', category: 'web', difficulty: 'hard', featured: false,
      title: 'Kanban Task Board',
      desc: 'Clone Trello with drag-and-drop boards, columns, and cards. Add Firebase for real-time sync so teams can collaborate live.',
      longDesc: 'Build a full-featured Kanban project management tool inspired by Trello. Users can create boards, add columns (To Do, In Progress, Done), and drag cards between them. Sync state in real-time with Firebase Firestore so multiple users see changes instantly. One of the most employer-impressive projects you can build.',
      tech: ['react', 'javascript'],
      tags: ['React', 'Firebase', 'Drag & Drop', 'Real-time'],
      skills: ['Drag-and-Drop API', 'Firestore Real-time', 'Component Architecture', 'Optimistic Updates'],
      requirements: [
        'Create, rename, and delete project boards',
        'Add, edit, and delete columns within a board',
        'Add task cards with title, description, labels, and due dates',
        'Implement drag-and-drop to reorder cards and move between columns',
        'Sync all changes in real-time to Firebase Firestore',
        'Invite collaborators to a board by email',
      ],
      resources: [
        { label: '@hello-pangea/dnd (DnD library)', url: 'https://github.com/hello-pangea/dnd' },
        { label: 'Firebase Firestore Docs', url: 'https://firebase.google.com/docs/firestore' },
      ],
      devs: 1580, time: '3–5 weeks',
    },

    {
      id: 'web-crypto-tracker', category: 'web', difficulty: 'medium', featured: false,
      title: 'Crypto Price Tracker',
      desc: 'Build a live cryptocurrency dashboard using the CoinGecko API — track prices, market caps, volume, and portfolio value in real time.',
      longDesc: 'Create a crypto price tracker similar to CoinMarketCap. Display live prices, 24h changes, market cap, and trading volume for 100+ cryptocurrencies. Add a personal portfolio tracker where users input holdings and see their total value update live. Great project for learning WebSockets, charting, and financial data handling.',
      tech: ['javascript', 'html-css'],
      tags: ['CoinGecko API', 'Chart.js', 'WebSockets', 'LocalStorage'],
      skills: ['Real-time Data', 'Chart.js', 'Financial Calculations', 'Table Sorting'],
      requirements: [
        'Display top 100 cryptocurrencies with live price updates',
        'Show 24h price change, market cap, and trading volume',
        'Click any coin to see a 7-day price chart',
        'Add coins to a portfolio and track total value',
        'Search and filter the coins list',
        'Auto-refresh prices every 30 seconds via polling',
      ],
      resources: [
        { label: 'CoinGecko API (Free)', url: 'https://www.coingecko.com/en/api' },
        { label: 'Chart.js Documentation', url: 'https://www.chartjs.org/docs/latest' },
      ],
      devs: 2100, time: '5–8 days',
    },

    {
      id: 'web-job-board', category: 'web', difficulty: 'hard', featured: false,
      title: 'Job Board Platform',
      desc: 'Build a job listing platform where companies can post jobs and developers can search, filter, and apply — styled like Linear or Levels.fyi.',
      longDesc: 'Create a full-stack job board with two user roles: employers who can post/manage job listings, and candidates who can search and filter jobs by role, stack, location, or salary range. Build the backend API with Node.js and Express, store data in MongoDB, and build a clean, minimal frontend with real authentication.',
      tech: ['react', 'node', 'javascript'],
      tags: ['Node.js', 'Express', 'MongoDB', 'JWT Auth'],
      skills: ['Role-Based Auth', 'REST API', 'Database Design', 'Search Filters'],
      requirements: [
        'Two user roles: employer and job seeker with separate dashboards',
        'Employers can create, edit, and close job listings',
        'Candidates can search jobs by title, tech stack, location, and salary',
        'Apply to jobs with a cover letter and profile link',
        'Email notification to employer on new application via SendGrid',
        'Bookmark jobs and track application status',
      ],
      resources: [
        { label: 'SendGrid Email API', url: 'https://docs.sendgrid.com' },
        { label: 'JSON Web Tokens', url: 'https://jwt.io/introduction' },
      ],
      devs: 760, time: '4–8 weeks',
    },

    {
      id: 'web-markdown-blog', category: 'web', difficulty: 'medium', featured: false,
      title: 'Markdown Blog Editor',
      desc: 'Build a side-by-side Markdown editor and preview with syntax highlighting, code blocks, image upload, and publish to a simple backend.',
      longDesc: 'Create a powerful browser-based markdown editor with live preview (like dev.to or Hashnode\'s editor). Support full CommonMark Markdown, code block syntax highlighting with Prism.js, image drag-and-drop upload, and saving draft posts to a backend. A great project for learning parsers, localStorage, and rich text handling.',
      tech: ['javascript', 'react', 'html-css'],
      tags: ['Marked.js', 'Prism.js', 'File Upload', 'LocalStorage'],
      skills: ['Markdown Parsing', 'Syntax Highlighting', 'File Handling', 'Rich Editors'],
      requirements: [
        'Side-by-side Markdown editor with live HTML preview',
        'Support full CommonMark spec (tables, code blocks, images, etc.)',
        'Syntax highlighting for code blocks using Prism.js',
        'Drag-and-drop or paste images to upload',
        'Auto-save drafts to localStorage every 30 seconds',
        'Export the post as a standalone HTML file',
      ],
      resources: [
        { label: 'Marked.js Parser', url: 'https://marked.js.org' },
        { label: 'Prism.js Syntax Highlighting', url: 'https://prismjs.com' },
      ],
      devs: 980, time: '1–2 weeks',
    },

    {
      id: 'web-maps-theme', category: 'web', difficulty: 'easy', featured: false,
      title: 'Custom Google Maps Theme',
      desc: 'Create and style a Google Map with a custom theme and marker images using the Google Maps JavaScript API and Google Cloud Platform.',
      longDesc: 'Create and style a Google Map with a custom theme and marker images using the Google Maps JavaScript API. You\'ll set up a Google Cloud project, use the Maps Styling Wizard to generate a JSON style, and load the map inside a webpage. Try building a themed map — cyberpunk, retro, nature — the sky\'s the limit.',
      tech: ['javascript', 'html-css'],
      tags: ['Google Maps API', 'GCP', 'CSS', 'JSON Config'],
      skills: ['API Setup', 'JSON Style Config', 'Map Markers', 'DOM Manipulation'],
      requirements: [
        'Set up a Google Cloud project and enable the Maps JavaScript API',
        'Create a custom map style using the Styling Wizard or JSON',
        'Add custom SVG or PNG marker images at specific coordinates',
        'Load and display the map inside a webpage with controls',
        'Add an info window that opens when clicking a marker',
        'Make the map fully responsive within its container',
      ],
      resources: [
        { label: 'Google Maps JS API Docs', url: 'https://developers.google.com/maps/documentation/javascript' },
        { label: 'Maps Styling Wizard', url: 'https://mapstyle.withgoogle.com' },
      ],
      devs: 5738, time: '1–2 weeks',
    },

    {
      id: 'web-image-gallery', category: 'web', difficulty: 'medium', featured: false,
      title: 'Image Search Gallery',
      desc: 'Build a sleek image search app powered by the Unsplash API with debounced search, masonry layout, and infinite scroll.',
      longDesc: 'Create a polished image search application that hooks into the Unsplash API. Implement debounced real-time search, display results in a responsive masonry grid, and add infinite scroll so users can keep discovering photos without clicking "next page". Download any photo in one click.',
      tech: ['javascript', 'react', 'html-css'],
      tags: ['Unsplash API', 'Masonry Grid', 'Infinite Scroll', 'Debounce'],
      skills: ['API Calls', 'Search Debounce', 'Masonry Layout', 'Intersection Observer'],
      requirements: [
        'Search for images using the Unsplash /search/photos endpoint',
        'Debounce search input to avoid excessive API calls',
        'Display results in a responsive CSS masonry grid',
        'Infinite scroll — load more results when reaching the bottom',
        'Show photographer credit with link to their Unsplash profile',
        'One-click full-resolution image download',
      ],
      resources: [
        { label: 'Unsplash Developer API', url: 'https://unsplash.com/developers' },
        { label: 'Intersection Observer API', url: 'https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API' },
      ],
      devs: 889, time: '3–5 days',
    },

    {
      id: 'web-expense-tracker', category: 'web', difficulty: 'medium', featured: false,
      title: 'Personal Expense Tracker',
      desc: 'A full-stack expense manager where users log, categorise, and visualise spending with monthly summaries and budget alerts.',
      longDesc: 'Build a personal finance app with Firebase backend. Users can log daily expenses by category (food, transport, entertainment), set monthly budgets, and track balance. Visualise spending breakdowns with Chart.js doughnut and bar charts. Add export to CSV and budget alert notifications.',
      tech: ['react', 'javascript', 'html-css'],
      tags: ['Chart.js', 'Firebase', 'CRUD', 'LocalStorage'],
      skills: ['Data Visualization', 'CRUD Operations', 'Budget Logic', 'Form Validation'],
      requirements: [
        'Add, edit, and delete expense entries with category and amount',
        'Set per-category monthly budget limits',
        'Visualise spending with doughnut (by category) and bar (by month) charts',
        'Show running balance and budget remaining per category',
        'Alert user when they exceed 80% of a budget',
        'Export expense history as CSV or PDF',
      ],
      resources: [
        { label: 'Chart.js Documentation', url: 'https://www.chartjs.org' },
        { label: 'Firebase Firestore', url: 'https://firebase.google.com/docs/firestore' },
      ],
      devs: 3201, time: '1–2 weeks',
    },

    {
      id: 'web-portfolio', category: 'web', difficulty: 'easy', featured: true,
      title: 'Animated Developer Portfolio',
      desc: 'Design and build a stunning, animated single-page portfolio with typewriter effects, project showcase, and a working contact form.',
      longDesc: 'Build a developer portfolio that actually gets you hired. Include an animated hero with typewriter effect, a skills section with animated progress bars, a projects showcase grid, an interactive timeline for experience, and a contact form that sends emails via EmailJS — no backend required.',
      tech: ['html-css', 'javascript'],
      tags: ['CSS Animations', 'GSAP', 'EmailJS', 'Responsive'],
      skills: ['CSS Animations', 'Responsive Design', 'Form Handling', 'Scroll Effects'],
      requirements: [
        'Animated hero section with typewriter/role-cycling effect',
        'Scroll-triggered section reveal animations',
        'Projects grid with hover effects and live/github links',
        'Skills section with animated progress indicators',
        'Experience timeline with alternating layout',
        'Contact form that sends emails without a backend using EmailJS',
        'Fully responsive from 320px mobile to 4K desktop',
      ],
      resources: [
        { label: 'GSAP Animation Library', url: 'https://greensock.com/gsap' },
        { label: 'EmailJS (No-backend email)', url: 'https://www.emailjs.com' },
        { label: 'Animate On Scroll (AOS)', url: 'https://michalsnik.github.io/aos' },
      ],
      devs: 7812, time: '1–3 days',
    },

    {
      id: 'web-chat-app', category: 'web', difficulty: 'hard', featured: false,
      title: 'Real-Time Chat Application',
      desc: 'Build a real-time messaging app with multiple rooms, user presence indicators, and message history — powered by Firebase or WebSockets.',
      longDesc: 'Create a full-featured chat application where users can create channels, send messages in real-time, see who is online, and view message history. Use Firebase Realtime Database or WebSockets for instant delivery. Add features like emoji reactions, file uploads, and typing indicators.',
      tech: ['react', 'javascript', 'node'],
      tags: ['WebSockets', 'Firebase', 'Real-time', 'Auth'],
      skills: ['Real-time DB', 'WebSocket Protocol', 'User Presence', 'File Uploads'],
      requirements: [
        'Create and join multiple chat rooms/channels',
        'Send and receive messages in real time (< 200ms)',
        'Show online/offline/typing presence for other users',
        'Display message history stored to Firebase or DB',
        'Send images and file attachments',
        'Add emoji reactions to messages',
      ],
      resources: [
        { label: 'Firebase Realtime Database', url: 'https://firebase.google.com/docs/database' },
        { label: 'Socket.IO for WebSockets', url: 'https://socket.io/docs' },
      ],
      devs: 1543, time: '2–4 weeks',
    },

    {
      id: 'web-downtime-monitor', category: 'web', difficulty: 'hard', featured: false,
      title: 'Downtime Monitoring with Alerts',
      desc: 'Build an automated uptime monitor with email/Slack alerts and a dashboard showing historical uptime for your websites.',
      longDesc: 'Build an automated downtime monitoring application with real-time alerts and uptime reports. Configure a cron job to ping your target URLs at regular intervals, log incident history, and fire Slack or email alerts when a site goes down. Build a clean dashboard to visualise uptime history.',
      tech: ['javascript', 'node', 'vue'],
      tags: ['Node.js', 'MongoDB', 'Express', 'Cron', 'Slack API'],
      skills: ['Cron Jobs', 'REST API', 'Database Modeling', 'Alerting Systems'],
      requirements: [
        'Check multiple URLs at configurable intervals using a cron job',
        'Trigger email and Slack webhook alerts when downtime detected',
        'Log incident start/end times and calculate uptime percentage',
        'Build a dashboard with uptime charts per URL',
        'Generate weekly email uptime reports',
        'Support HTTP status code and keyword-match check types',
      ],
      resources: [
        { label: 'node-cron Scheduler', url: 'https://github.com/node-cron/node-cron' },
        { label: 'Slack Incoming Webhooks', url: 'https://api.slack.com/messaging/webhooks' },
      ],
      devs: 696, time: '2–4 weeks',
    },

    // ── MOBILE ────────────────────────────────────────────────

    {
      id: 'mob-temp-converter', category: 'mobile', difficulty: 'easy', featured: false,
      title: 'Temperature Converter App',
      desc: 'A simple, clean mobile app to convert temperatures between Celsius, Fahrenheit, and Kelvin with animated transitions.',
      longDesc: 'Build a polished temperature conversion app as a mobile application. This beginner-friendly project teaches you mobile UI fundamentals, input handling, and state management. Extend it with a conversion history, haptic feedback, and a dark/light mode toggle.',
      tech: ['swift', 'java', 'react-native'],
      tags: ['Swift', 'React Native', 'Haptics', 'Mobile UI'],
      skills: ['Mobile UI Layout', 'User Input', 'State Management', 'Animations'],
      requirements: [
        'Convert between Celsius, Fahrenheit, and Kelvin in real time',
        'Animated number transition on conversion',
        'Scroll list of recent conversions',
        'Haptic feedback on conversion (on native iOS/Android)',
        'Dark/light mode toggle',
        'Support landscape orientation',
      ],
      resources: [
        { label: 'React Native Docs', url: 'https://reactnative.dev/docs/getting-started' },
        { label: 'Expo (Quick start)', url: 'https://docs.expo.dev' },
      ],
      devs: 812, time: '1–3 days',
    },

    {
      id: 'mob-food-journal', category: 'mobile', difficulty: 'medium', featured: false,
      title: 'Food Journal Mobile App',
      desc: 'Capture photos and log nutritional info about your meals. Track macros and view nutrition trends in weekly charts.',
      longDesc: 'Build a mobile food tracking diary where users can photograph meals, log calories and macronutrients, and visualise eating patterns over time. Access the camera API, store data locally, and chart weekly nutrition summaries.',
      tech: ['swift', 'java', 'react-native'],
      tags: ['Camera API', 'Local DB', 'Chart.js', 'File Storage'],
      skills: ['Camera Integration', 'Local Database', 'Data Visualization', 'Forms'],
      requirements: [
        'Capture or import photos from the camera roll for each meal',
        'Log meal name, time, calories, and macronutrients (protein/carbs/fat)',
        'View daily nutrition totals vs. your goals',
        'Weekly nutrition charts showing calorie and macro trends',
        'Search past meals to re-log favourite foods quickly',
        'Export journal as a PDF weekly summary',
      ],
      resources: [
        { label: 'Expo Camera API', url: 'https://docs.expo.dev/versions/latest/sdk/camera' },
        { label: 'Victory Native Charts', url: 'https://formidable.com/open-source/victory/docs/native' },
      ],
      devs: 473, time: '2–3 weeks',
    },

    {
      id: 'mob-invoice-app', category: 'mobile', difficulty: 'hard', featured: false,
      title: 'Invoicing & Payment Reminder App',
      desc: 'Generate, send, and track invoices from your phone. Automated overdue payment reminders keep clients on schedule.',
      longDesc: 'Build a mobile invoicing app for freelancers. Create professional PDF invoices, email them to clients, track payment status, and send automated follow-up reminders when invoices are overdue. Integrate Stripe to accept card payments directly from the invoice link.',
      tech: ['react-native', 'node', 'javascript'],
      tags: ['Stripe', 'Push Notifications', 'PDF Generation', 'Email'],
      skills: ['PDF Generation', 'Payment API', 'Push Notifications', 'Backend Integration'],
      requirements: [
        'Create and customise invoice templates with logo and brand colour',
        'Add line items, tax, and discount to invoices',
        'Email invoices as PDF to clients directly from the app',
        'Track payment status: draft, sent, viewed, paid, overdue',
        'Auto-send overdue payment reminders on a schedule',
        'Stripe payment link on the invoice so clients can pay by card',
      ],
      resources: [
        { label: 'Stripe Docs', url: 'https://stripe.com/docs' },
        { label: 'React Native PDF', url: 'https://github.com/wonday/react-native-pdf' },
      ],
      devs: 1111, time: '3–6 weeks',
    },

    {
      id: 'mob-fitness-tracker', category: 'mobile', difficulty: 'medium', featured: false,
      title: 'Fitness Workout Tracker',
      desc: 'Log workouts, track sets/reps/weight, and visualise strength progress over time with monthly charts and personal records.',
      longDesc: 'Build a gym workout tracker app. Users create custom workout routines, log sets and reps during a session, and track progressive overload over time. Show monthly volume charts and automatically highlight personal records. A real-world app that thousands of developers actually use.',
      tech: ['react-native', 'swift'],
      tags: ['SQLite', 'React Native', 'Charts', 'Local Storage'],
      skills: ['SQLite Database', 'Complex Forms', 'Data Visualization', 'Timer'],
      requirements: [
        'Create custom exercises with name, muscle group, and equipment',
        'Build workout routines from saved exercises',
        'Log sets, reps, and weight during an active workout session',
        'In-workout rest timer with haptic alert',
        'View monthly volume and frequency charts per muscle group',
        'Highlight personal records (PRs) in the workout history',
      ],
      resources: [
        { label: 'Expo SQLite', url: 'https://docs.expo.dev/versions/latest/sdk/sqlite' },
        { label: 'React Native Gifted Charts', url: 'https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts' },
      ],
      devs: 620, time: '2–4 weeks',
    },

    {
      id: 'mob-habit-tracker', category: 'mobile', difficulty: 'medium', featured: false,
      title: 'Habit Tracker App',
      desc: 'Track daily habits, build streaks, and get gentle push notification reminders — with a beautiful calendar heatmap view.',
      longDesc: 'Create a minimalist habit tracking app inspired by Streaks and Habitica. Users define daily habits, check them off each day, keep track of streaks, and see a GitHub-style heatmap calendar showing their consistency. Push notifications remind them at their chosen time.',
      tech: ['react-native', 'swift'],
      tags: ['Push Notifications', 'Heatmap', 'Streak Logic', 'SQLite'],
      skills: ['Push Notifications', 'Date Logic', 'Streak Calculation', 'Calendar UI'],
      requirements: [
        'Add habits with name, icon, colour, and daily reminder time',
        'Check off each habit for today with a satisfying animation',
        'Calculate and display the current streak for each habit',
        'Show a GitHub-style heatmap calendar of completion history',
        'Daily push notifications at the user\'s set reminder time',
        'Weekly summary notification showing completion rate',
      ],
      resources: [
        { label: 'Expo Notifications', url: 'https://docs.expo.dev/versions/latest/sdk/notifications' },
        { label: 'react-native-calendars', url: 'https://github.com/wix/react-native-calendars' },
      ],
      devs: 890, time: '1–3 weeks',
    },

    // ── TOOLS ─────────────────────────────────────────────────

    {
      id: 'tool-slack-bot', category: 'tool', difficulty: 'easy', featured: false,
      title: 'Slack Bot: PageSpeed Insights',
      desc: 'A Slack bot that fetches Google PageSpeed Insights scores for any URL — slash command + scheduled weekly reports.',
      longDesc: 'Build a Slack bot using the Slack Bolt framework that responds to the /pagespeed <url> command, fetches the Google PageSpeed Insights API, and posts a formatted score card to the channel. Extend it to run weekly automated scans for a list of URLs your team cares about.',
      tech: ['javascript', 'node'],
      tags: ['Slack Bolt', 'Node.js', 'PageSpeed API', 'Cron'],
      skills: ['Slack Bolt SDK', 'REST API', 'Webhook Handling', 'Scheduled Jobs'],
      requirements: [
        'Respond to /pagespeed <url> slash command in Slack',
        'Fetch performance, accessibility, SEO, and best-practices scores',
        'Format a rich block message with scores and a traffic-light emoji',
        'Show mobile vs. desktop score breakdown',
        'Schedule weekly scans for a configured list of URLs',
        'Deploy to a free hosting service like Railway',
      ],
      resources: [
        { label: 'Slack Bolt for JS', url: 'https://slack.dev/bolt-js/concepts' },
        { label: 'PageSpeed Insights API', url: 'https://developers.google.com/speed/docs/insights/v5/get-started' },
      ],
      devs: 395, time: '2–4 days',
    },

    {
      id: 'tool-web-scraper', category: 'tool', difficulty: 'easy', featured: false,
      title: 'Web Scraper for News Articles',
      desc: 'Extract the headline, author, date, and body text of any news article given its URL — export to JSON, CSV, or plain text.',
      longDesc: 'Build a CLI web scraper using Python and BeautifulSoup that extracts structured content from any news article URL. Handle common HTML patterns, detect paywalls, strip ads and nav menus, and export clean article data. Similar tech is used in price trackers and SEO audit tools.',
      tech: ['python'],
      tags: ['Python', 'BeautifulSoup', 'Requests', 'CLI'],
      skills: ['HTML Parsing', 'HTTP Requests', 'Data Extraction', 'CLI Design'],
      requirements: [
        'Accept a URL as a CLI argument',
        'Extract headline, author, publication date, and body text',
        'Strip navigation, ads, and footer content from the output',
        'Handle multi-page articles by following "next page" links',
        'Export results as JSON, CSV, or plain text via --format flag',
        'Detect and report paywall pages gracefully',
      ],
      resources: [
        { label: 'BeautifulSoup Docs', url: 'https://www.crummy.com/software/BeautifulSoup/bs4/doc' },
        { label: 'Requests Library', url: 'https://docs.python-requests.org' },
      ],
      devs: 2987, time: '2–3 days',
    },

    {
      id: 'tool-bg-jobs', category: 'tool', difficulty: 'medium', featured: false,
      title: 'Background Job System',
      desc: 'Build a background job processor with async queues, retry logic with backoff, and a status dashboard — a cornerstone of modern backends.',
      longDesc: 'Design and build a background job processing system that can enqueue, process, retry, and track async tasks. This is a core infrastructure component used by virtually every production web application. Learn about queue data structures, worker concurrency, dead-letter queues, and observability.',
      tech: ['node', 'php', 'java', 'python', 'ruby'],
      tags: ['Redis', 'Queue', 'Worker Pool', 'REST API'],
      skills: ['Queue Design', 'Worker Concurrency', 'Error Handling', 'API Design'],
      requirements: [
        'Enqueue jobs with payload via a REST API endpoint',
        'Process jobs with a configurable worker pool (N concurrent workers)',
        'Retry failed jobs with exponential backoff (max 3 retries)',
        'Move permanently-failed jobs to a dead-letter queue',
        'REST API to check job status: queued, running, done, failed',
        'Simple web dashboard showing queue depth, throughput, and error rate',
      ],
      resources: [
        { label: 'Bull Queue for Node.js', url: 'https://github.com/OptimalBits/bull' },
        { label: 'Celery for Python', url: 'https://docs.celeryq.dev' },
      ],
      devs: 865, time: '2–4 weeks',
    },

    {
      id: 'tool-github-analyzer', category: 'tool', difficulty: 'medium', featured: false,
      title: 'GitHub Repository Analyzer',
      desc: 'Analyse any public GitHub repo\'s commit history, contributor activity, and issue trends. Export a visual HTML report.',
      longDesc: 'Build a CLI tool (or web app) that accepts a GitHub repository URL and generates a comprehensive analytics report using the GitHub REST API. Visualise commit frequency, top contributors, issue open/close rates, PR merge times, and code growth over time.',
      tech: ['python', 'javascript'],
      tags: ['GitHub REST API', 'Pandas', 'Charts', 'CLI'],
      skills: ['API Pagination', 'Data Analysis', 'Data Visualization', 'Report Generation'],
      requirements: [
        'Fetch repo stats via GitHub REST API (with pagination handling)',
        'Analyse commit frequency by day-of-week and hour',
        'Identify top contributors by commit count and lines changed',
        'Visualise issue open/close rate over time with a chart',
        'Calculate average PR review and merge time',
        'Export a complete report as a self-contained HTML file',
      ],
      resources: [
        { label: 'GitHub REST API Docs', url: 'https://docs.github.com/en/rest' },
        { label: 'PyGitHub Library', url: 'https://pygithub.readthedocs.io' },
      ],
      devs: 1204, time: '1–2 weeks',
    },

    {
      id: 'tool-cli-todo', category: 'tool', difficulty: 'easy', featured: false,
      title: 'Feature-Rich CLI Todo App',
      desc: 'A command-line todo manager with projects, due dates, priorities, and tags — persists to a local JSON file.',
      longDesc: 'Build a powerful terminal todo manager that beats the simplicity of plain text files. Support sub-tasks, due dates, priorities, tags, and project grouping. Colourised terminal output makes it delightful to use. Write unit tests for all business logic.',
      tech: ['python', 'javascript', 'ruby'],
      tags: ['CLI', 'Argparse', 'File I/O', 'JSON', 'Colors'],
      skills: ['CLI Argument Parsing', 'File I/O', 'Data Serialization', 'Unit Testing'],
      requirements: [
        'add, done, edit, delete, and list tasks via CLI commands',
        'Group tasks by project with --project flag',
        'Set due dates and show overdue tasks with red highlighting',
        'Add priority levels (high, medium, low) and tag tasks',
        'Search/filter tasks by keyword, project, tag, or due date',
        'Persist all tasks to a local JSON file in the user\'s home directory',
      ],
      resources: [
        { label: 'Python Click Library', url: 'https://click.palletsprojects.com' },
        { label: 'Rich Terminal Library', url: 'https://github.com/Textualize/rich' },
      ],
      devs: 2178, time: '2–5 days',
    },

    {
      id: 'tool-pdf-generator', category: 'tool', difficulty: 'medium', featured: false,
      title: 'PDF Report Generator CLI',
      desc: 'A CLI tool that takes a JSON data file and a Jinja2 template and outputs a beautifully formatted professional PDF report.',
      longDesc: 'Build a command-line tool that generates professional PDF reports from structured data. Input a JSON data file and a Jinja2/Handlebars HTML template; output a pixel-perfect PDF. Useful for invoices, analytics reports, certificates, and CVs. Learn template engines, PDF rendering, and CLI tool design.',
      tech: ['python', 'node'],
      tags: ['Python', 'Jinja2', 'WeasyPrint', 'CLI'],
      skills: ['Template Engines', 'PDF Rendering', 'CLI Design', 'HTML/CSS → PDF'],
      requirements: [
        'Accept --data (JSON file) and --template (HTML/Jinja2) as CLI args',
        'Render the template with the data using Jinja2 or Handlebars',
        'Convert the rendered HTML to a PDF using WeasyPrint or Puppeteer',
        'Support headers, footers, and page numbers in the PDF',
        'Batch mode: process a folder of JSON files into multiple PDFs',
        'Include a set of 3+ starter templates (invoice, report, certificate)',
      ],
      resources: [
        { label: 'WeasyPrint Docs', url: 'https://weasyprint.org' },
        { label: 'Jinja2 Template Docs', url: 'https://jinja.palletsprojects.com' },
        { label: 'Puppeteer PDF', url: 'https://pptr.dev/#generating-pdf' },
      ],
      devs: 540, time: '1–2 weeks',
    },

    {
      id: 'tool-readme-generator', category: 'tool', difficulty: 'easy', featured: false,
      title: 'GitHub README Generator',
      desc: 'A web-based tool that generates beautiful, structured GitHub README.md files via an interactive form — with live preview.',
      longDesc: 'Build an interactive web tool where developers fill out a form (project name, description, installation, usage, screenshots, badges, license) and get a perfectly formatted README.md file. Show a live Markdown preview as they type. Download the file with one click.',
      tech: ['python', 'javascript', 'html-css'],
      tags: ['Markdown', 'Form Builder', 'Live Preview', 'Shields.io'],
      skills: ['Markdown Generation', 'Dynamic Forms', 'Live Preview', 'File Download'],
      requirements: [
        'Multi-section form: title, description, tech stack, installation, usage',
        'Live Markdown preview rendered as the user types',
        'Add optional sections: screenshots, badges, contributing, license',
        'One-click copy to clipboard or download as README.md',
        'Include common badge templates from Shields.io',
        'Section drag-and-drop reordering',
      ],
      resources: [
        { label: 'Shields.io Badges', url: 'https://shields.io' },
        { label: 'Marked.js', url: 'https://marked.js.org' },
      ],
      devs: 1820, time: '2–5 days',
    },

    {
      id: 'tool-email-newsletter', category: 'tool', difficulty: 'medium', featured: false,
      title: 'Automated Email Newsletter',
      desc: 'Build a newsletter pipeline that fetches content from RSS feeds, renders a beautiful HTML email, and sends it on a schedule.',
      longDesc: 'Create an automated newsletter system that aggregates content from RSS feeds you configure, formats it into a branded HTML email using a template, and sends it to subscribers via SendGrid on a weekly schedule. Build a simple web UI to manage subscribers and view send history.',
      tech: ['python', 'node'],
      tags: ['SendGrid', 'RSS Parsing', 'HTML Email', 'Cron'],
      skills: ['Email HTML', 'RSS/Feed Parsing', 'Cron Scheduling', 'Subscriber Management'],
      requirements: [
        'Configure a list of RSS/Atom feed URLs to aggregate',
        'Fetch and parse feed items (title, summary, link, image) weekly',
        'Render a responsive HTML email template from the fetched content',
        'Send the email to your subscriber list via SendGrid API',
        'Web UI to subscribe/unsubscribe with double opt-in confirmation',
        'Store send history and open rate (via tracking pixel) in a DB',
      ],
      resources: [
        { label: 'SendGrid Docs', url: 'https://docs.sendgrid.com' },
        { label: 'feedparser (Python)', url: 'https://feedparser.readthedocs.io' },
      ],
      devs: 490, time: '1–2 weeks',
    },

    {
      id: 'tool-file-organizer', category: 'tool', difficulty: 'easy', featured: false,
      title: 'File Organizer Script',
      desc: 'A Python script that automatically sorts files in a directory into categorised sub-folders based on extension, date, or custom rules.',
      longDesc: 'Build a smart file organisation utility that cleans up your Downloads or Desktop folder. It sorts files into sub-folders by extension (images, videos, docs), by creation/modification date, or by user-defined rules. Run it on demand or schedule it as a cron job.',
      tech: ['python'],
      tags: ['Python', 'OS Module', 'Pathlib', 'CLI', 'File System'],
      skills: ['File System Ops', 'Regular Expressions', 'CLI Tools', 'Scheduling'],
      requirements: [
        'Scan a target directory and categorise files by extension',
        'Move files into sub-folders: Images/, Videos/, Documents/, Archives/, etc.',
        'Option to sort by year-month date instead of extension',
        'Define custom rules in a config YAML file (e.g. *.pdf → Reports/)',
        'Dry-run mode shows what WOULD be moved without actually moving',
        'Undo last run by reverting moves from a log file',
      ],
      resources: [
        { label: 'Python Pathlib Docs', url: 'https://docs.python.org/3/library/pathlib.html' },
        { label: 'Python shutil Module', url: 'https://docs.python.org/3/library/shutil.html' },
      ],
      devs: 3200, time: '1–3 days',
    },

    // ── AI / ML ───────────────────────────────────────────────

    {
      id: 'ai-sentiment-analyzer', category: 'ai', difficulty: 'medium', featured: false,
      title: 'Sentiment Analyzer Tool',
      desc: 'Analyse the sentiment of any text (positive/negative/neutral) with a confidence score using NLTK or a pretrained transformer model.',
      longDesc: 'Build a sentiment analysis tool that can classify text (tweets, reviews, comments) as positive, negative, or neutral and return a confidence score. Build both a CLI interface and a simple REST API to expose the model. Compare two approaches: lexicon-based (VADER) vs. a pre-trained transformer (BERT).',
      tech: ['python'],
      tags: ['Python', 'NLTK', 'HuggingFace', 'Flask', 'NLP'],
      skills: ['NLP Basics', 'Model Inference', 'REST API', 'Text Preprocessing'],
      requirements: [
        'Classify input text as positive, negative, or neutral',
        'Return a confidence score (0–1) for each sentiment class',
        'Implement using VADER (lexicon) and compare with a transformer model',
        'Build a Flask REST API: POST /analyze → { sentiment, confidence }',
        'Accept bulk input: analyse a list of texts in one API call',
        'Simple web UI where you paste text and see the result live',
      ],
      resources: [
        { label: 'VADER Sentiment (NLTK)', url: 'https://www.nltk.org/howto/sentiment.html' },
        { label: 'HuggingFace Transformers', url: 'https://huggingface.co/docs/transformers' },
      ],
      devs: 850, time: '1–2 weeks',
    },

    {
      id: 'ai-chatbot', category: 'ai', difficulty: 'medium', featured: true,
      title: 'AI Chatbot with OpenAI',
      desc: 'Build a feature-rich AI chatbot using the ChatGPT API — with conversation memory, system prompts, streaming, and a polished chat UI.',
      longDesc: 'Create a full-featured conversational AI chatbot powered by OpenAI\'s GPT-4o. Build a polished chat interface with streaming responses, adjustable system prompts (personas), conversation history, token counter, and the ability to save/load past chats. Deploy to Vercel for free.',
      tech: ['javascript', 'react', 'python'],
      tags: ['OpenAI API', 'Streaming', 'React', 'Chat UI'],
      skills: ['OpenAI API', 'Streaming Responses', 'Chat State', 'Prompt Engineering'],
      requirements: [
        'Chat interface with streaming token-by-token responses',
        'Maintain conversation history as context for follow-up questions',
        'Configurable system prompt to give the AI a custom persona',
        'Live token counter and estimated cost display',
        'Save and load past conversations from localStorage or a backend',
        'Copy any message to clipboard with one click',
      ],
      resources: [
        { label: 'OpenAI Node/Python SDK', url: 'https://platform.openai.com/docs/libraries' },
        { label: 'OpenAI Streaming Guide', url: 'https://platform.openai.com/docs/api-reference/streaming' },
      ],
      devs: 1650, time: '3–7 days',
    },

    {
      id: 'ai-image-caption', category: 'ai', difficulty: 'hard', featured: false,
      title: 'Image Caption Generator',
      desc: 'Upload any image and automatically generate a descriptive caption using a pretrained vision-language model (BLIP or GPT-4 Vision).',
      longDesc: 'Build an image captioning application using a pretrained vision-language model such as BLIP (Salesforce) or GPT-4 Vision. Build a web interface where users upload an image and receive an automatically generated caption. Extend it to batch-caption a folder of images via CLI. Learn multimodal AI inference and image processing.',
      tech: ['python', 'javascript'],
      tags: ['Python', 'BLIP', 'HuggingFace', 'PIL', 'Flask'],
      skills: ['Vision-Language Models', 'Image Processing', 'Model Inference', 'Flask API'],
      requirements: [
        'Accept image upload via a web UI or CLI path argument',
        'Run the image through a pre-trained BLIP or GPT-4V model',
        'Return multiple caption candidates with confidence scores',
        'Display the image alongside its generated caption in the UI',
        'Batch process a folder of images and save captions to a CSV',
        'Optional: generate captions in multiple languages via translation',
      ],
      resources: [
        { label: 'BLIP Model (HuggingFace)', url: 'https://huggingface.co/Salesforce/blip-image-captioning-large' },
        { label: 'GPT-4 Vision Docs', url: 'https://platform.openai.com/docs/guides/vision' },
      ],
      devs: 310, time: '2–3 weeks',
    },

    {
      id: 'ai-text-summarizer', category: 'ai', difficulty: 'medium', featured: false,
      title: 'Article Text Summarizer',
      desc: 'Paste a long article or URL and get a concise bullet-point or paragraph summary using HuggingFace or OpenAI — with adjustable summary length.',
      longDesc: 'Build a text summarization tool that accepts long-form text or a URL and returns a concise summary. Compare extractive (picking key sentences) vs. abstractive (generating new text) summarization. Build a clean web interface and a REST API endpoint. Add adjustable summary length control.',
      tech: ['python', 'javascript'],
      tags: ['Python', 'HuggingFace', 'BART', 'Flask', 'Transformers'],
      skills: ['Summarization Models', 'Text Chunking', 'REST API', 'NLP Pipelines'],
      requirements: [
        'Accept raw text paste or a URL (and scrape its content)',
        'Summarize using BART or a PEGASUS model from HuggingFace',
        'Adjustable summary length: short / medium / detailed',
        'Show both an extractive and abstractive summary for comparison',
        'REST API endpoint: POST /summarize → { summary, word_count }',
        'Copy summary to clipboard and download as .txt',
      ],
      resources: [
        { label: 'HuggingFace Summarization', url: 'https://huggingface.co/tasks/summarization' },
        { label: 'BART Model Card', url: 'https://huggingface.co/facebook/bart-large-cnn' },
      ],
      devs: 720, time: '1–2 weeks',
    },

    // ── GAMES ─────────────────────────────────────────────────

    {
      id: 'game-wordle', category: 'game', difficulty: 'medium', featured: true,
      title: 'Wordle Clone',
      desc: 'Recreate the viral word-guessing game with hard mode, colour-blind mode, word statistics, and a daily word mechanic.',
      longDesc: 'Clone the massively popular Wordle game with all its features. Implement the 6-guess grid, colour-coded letter feedback (green/yellow/grey), on-screen keyboard, guess validation against a word list, daily word seed, hard mode (must use revealed letters), and a statistics modal with win-rate and streak data.',
      tech: ['javascript', 'html-css'],
      tags: ['JavaScript', 'HTML/CSS', 'Vanilla JS', 'Game Logic'],
      skills: ['Game Logic', 'Colour Feedback Algorithm', 'Animations', 'localStorage'],
      requirements: [
        'Six-row guess grid with 5-letter input per row',
        'Colour feedback: green (correct position), yellow (wrong position), grey (not in word)',
        'On-screen keyboard that updates colours after each guess',
        'Guess validation against a dictionary of valid 5-letter words',
        'Daily word mode: same word for all users each day, seeded by date',
        'Hard mode: must use revealed green/yellow letters in subsequent guesses',
        'Statistics modal: games played, win %, current streak, max streak',
      ],
      resources: [
        { label: 'Word List Data', url: 'https://github.com/tabatkins/wordle-list' },
        { label: 'Seeded RNG explanation', url: 'https://stackoverflow.com/questions/521295/seeding-the-random-number-generator-in-javascript' },
      ],
      devs: 2800, time: '1–2 weeks',
    },

    {
      id: 'game-chess', category: 'game', difficulty: 'hard', featured: false,
      title: 'Chess Game (2-Player)',
      desc: 'Build a fully functional browser-based chess game with legal move validation, check/checkmate detection, and a game history panel.',
      longDesc: 'Implement a complete chess game in the browser. Render the 8×8 board, verify legal moves for all piece types including special moves (castling, en passant, pawn promotion), detect check and checkmate, and display the move history in algebraic notation. Optionally add a basic AI opponent using minimax.',
      tech: ['javascript', 'html-css'],
      tags: ['JavaScript', 'Canvas/DOM', 'Game Logic', 'Chess Engine'],
      skills: ['Chess Move Logic', 'Board State Management', 'Minimax Algorithm', 'DOM Rendering'],
      requirements: [
        'Render an 8×8 chessboard with correct piece placement',
        'Legal move highlighting when a piece is selected',
        'Enforce all standard chess rules including castling, en passant, promotion',
        'Detect and display check, checkmate, and stalemate',
        'Move history panel in algebraic notation (e.g. e4, Nf3, O-O)',
        'Optional: basic AI opponent using minimax with alpha-beta pruning',
      ],
      resources: [
        { label: 'Chess.js (Move Validation)', url: 'https://github.com/jhlywa/chess.js' },
        { label: 'Chessboard.js (Rendering)', url: 'https://chessboardjs.com' },
        { label: 'Minimax Algorithm Explainer', url: 'https://www.chessprogramming.org/Minimax' },
      ],
      devs: 640, time: '3–6 weeks',
    },

    {
      id: 'game-tetris', category: 'game', difficulty: 'hard', featured: false,
      title: 'Tetris Clone',
      desc: 'Build a complete browser Tetris implementation using Canvas — with all 7 tetrominoes, line clearing, gravity, and a scoring system.',
      longDesc: 'Implement the classic Tetris game using the HTML5 Canvas API. Render the 10×20 grid, handle all 7 tetromino shapes, implement rotation using the SRS rotation system, simulate gravity that speeds up over time, detect line clears (with animation), and implement the official Tetris scoring system. Add a game loop, pause, and high score persistence.',
      tech: ['javascript', 'html-css'],
      tags: ['Canvas API', 'Game Loop', 'JavaScript', 'requestAnimationFrame'],
      skills: ['Canvas API', 'Game Loop Design', 'Collision Detection', 'State Machine'],
      requirements: [
        'Render a 10×20 Tetris grid on HTML5 Canvas',
        'Implement all 7 Tetrimino shapes with correct colours',
        'Rotation using the Super Rotation System (SRS) with wall kicks',
        'Gravity that increases speed every 10 lines cleared',
        'Detect and animate line clears (flash + collapse)',
        'Score system: single/double/triple/tetris bonuses',
        'Next-piece preview panel, pause, and game over screen',
      ],
      resources: [
        { label: 'Tetris Guideline (SRS)', url: 'https://tetris.wiki/Super_Rotation_System' },
        { label: 'MDN Canvas Tutorial', url: 'https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial' },
      ],
      devs: 890, time: '2–4 weeks',
    },

    {
      id: 'game-memory-card', category: 'game', difficulty: 'easy', featured: false,
      title: 'Memory Card Game',
      desc: 'Build a polished flip-card memory matching game with difficulty levels, a move counter, timer, and smooth card flip animations.',
      longDesc: 'Create the classic memory card matching game with smooth CSS 3D flip animations. Players flip two cards at a time trying to find matching pairs. Track moves, time, and best score. Add difficulty levels (4×4, 6×6, 8×8), themed card faces (emojis, icons, or images from an API), and a celebratory win animation.',
      tech: ['javascript', 'html-css'],
      tags: ['JavaScript', 'CSS Animations', 'CSS Grid', 'Local Storage'],
      skills: ['CSS 3D Transforms', 'Game State Logic', 'Timers', 'Randomisation'],
      requirements: [
        'Grid of face-down cards that flip on click to reveal an emoji/image',
        'Match pairs — matched cards stay revealed, unmatched flip back',
        'Move counter and elapsed timer displayed during play',
        'Three difficulty levels: 4×4 (easy), 6×6 (medium), 8×8 (hard)',
        'Smooth CSS 3D card flip animation',
        'Confetti win animation when all pairs are matched',
        'Save best time and fewest moves per difficulty to localStorage',
      ],
      resources: [
        { label: 'CSS 3D Transforms Guide', url: 'https://css-tricks.com/almanac/properties/t/transform' },
        { label: 'canvas-confetti library', url: 'https://github.com/catdad/canvas-confetti' },
      ],
      devs: 3100, time: '2–4 days',
    },

  ]; // end window.LF_PROJECTS

  // ── Demo Community Projects (shown in Community tab for teacher demo) ──
  window.LF_COMMUNITY_DEMO = [
    {
      id: 'comm-student-budget',
      category: 'web', difficulty: 'medium',
      title: 'Student Budget Tracker',
      desc: 'A web app that helps college students manage their monthly budget — track expenses, set category limits, and get visual breakdowns of their spending.',
      longDesc: 'I built this after struggling with my own finances in first year. It lets you input your monthly allowance, log daily expenses by category (food, transport, books, fun), and shows you live charts of how much you have left. Simple and really useful for students.',
      tech: ['javascript', 'html-css'],
      tags: ['Chart.js', 'LocalStorage', 'HTML/CSS', 'Forms'],
      skills: ['Budget Logic', 'Data Visualization', 'CRUD', 'Form Validation'],
      requirements: [
        'Enter a monthly budget on first load',
        'Add expenses with amount, category, and optional note',
        'Show a live doughnut chart of spending by category',
        'Highlight categories that are near or over budget in red',
        'Show a summary of remaining balance and days left in month',
        'Persist all data in localStorage (no login needed)',
      ],
      resources: [
        { label: 'Chart.js Docs', url: 'https://www.chartjs.org/docs/latest' },
        { label: 'MDN localStorage', url: 'https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage' },
      ],
      authorName: 'Priya Sharma',
      authorGithub: 'https://github.com/priyasharma-dev',
      devs: 42, isUserSubmitted: true, status: 'published',
      createdAt: new Date('2026-03-15'),
    },
    {
      id: 'comm-quiz-app',
      category: 'web', difficulty: 'easy',
      title: 'Classroom Quiz App',
      desc: 'An interactive quiz platform for students — teachers can create quizzes with multiple-choice questions and students join with a code to answer live.',
      longDesc: 'Our teacher always used Kahoot but we decided to build our own. This project lets a teacher create a quiz (questions + options + correct answer), share a room code, and students join on their phones. Answers are collected and a live leaderboard updates after each question. Built during our college hackathon.',
      tech: ['javascript', 'html-css', 'node'],
      tags: ['WebSockets', 'Node.js', 'Room Codes', 'Leaderboard'],
      skills: ['Real-time Data', 'State Sync', 'Multi-user Logic', 'WebSockets'],
      requirements: [
        'Teacher creates a quiz with custom questions and selects correct answer',
        'Generate a 6-character room code for students to join',
        'Students join on their phone and see questions in sync with teacher',
        'After each question show the correct answer and update leaderboard',
        'Final results screen with rank, score, and correct answers',
        'Works on mobile without installing any app',
      ],
      resources: [
        { label: 'Socket.IO Docs', url: 'https://socket.io/docs/v4' },
        { label: 'Node.js Express', url: 'https://expressjs.com' },
      ],
      authorName: 'Arjun Mehta',
      authorGithub: 'https://github.com/arjunm',
      devs: 87, isUserSubmitted: true, status: 'published',
      createdAt: new Date('2026-03-20'),
    },
    {
      id: 'comm-recipe-share',
      category: 'web', difficulty: 'easy',
      title: 'Recipe Sharing Platform',
      desc: 'A community-driven recipe website where users can post their own recipes with photos, ingredients, and steps — and search what to cook based on ingredients they have.',
      longDesc: 'My mom has hundreds of recipes in a notebook and I wanted to put them online. This project lets users submit recipes with a photo, list of ingredients, and step-by-step cooking instructions. Other users can search by ingredient name to find what they can cook with what is already in their kitchen.',
      tech: ['html-css', 'javascript'],
      tags: ['HTML/CSS', 'LocalStorage', 'Search', 'Forms'],
      skills: ['CRUD Operations', 'Search Filtering', 'Image Handling', 'Card Layouts'],
      requirements: [
        'Submit a recipe with title, description, ingredient list, and steps',
        'Upload a photo or paste an image URL for the recipe',
        'Browse all recipes in a responsive card grid',
        'Search recipes by ingredient — finds all recipes that use that ingredient',
        'Filter by cuisine type (Indian, Italian, Mexican, etc.)',
        'Recipe detail page shows full ingredient list and numbered steps',
      ],
      resources: [
        { label: 'MDN File API (image upload)', url: 'https://developer.mozilla.org/en-US/docs/Web/API/File_API' },
        { label: 'CSS Grid Guide', url: 'https://css-tricks.com/snippets/css/complete-guide-grid' },
      ],
      authorName: 'Sneha Kulkarni',
      authorGithub: '',
      devs: 23, isUserSubmitted: true, status: 'published',
      createdAt: new Date('2026-03-25'),
    },
    {
      id: 'comm-attendance-tracker',
      category: 'tool', difficulty: 'medium',
      title: 'College Attendance Tracker',
      desc: 'Track subject-wise attendance, calculate your percentage, and get early warnings before you fall below the 75% threshold required for exams.',
      longDesc: 'Every semester I keep losing track of my attendance and then panic near exams. I built this tool to solve that. You add your subjects, mark each class as Present, Absent, or Cancelled, and the app tells you how many more classes you can miss before falling below 75%. It sends a browser notification when you get to 80%.',
      tech: ['javascript', 'html-css'],
      tags: ['LocalStorage', 'Notifications', 'Math Logic', 'Calendar'],
      skills: ['Date Logic', 'Percentage Calculation', 'Push Notifications', 'CRUD'],
      requirements: [
        'Add subjects with total weekly classes per subject',
        'Mark attendance for each class: Present, Absent, or Cancelled',
        'Calculate and display current attendance % per subject',
        'Show how many classes can still be missed before hitting 75%',
        'Browser notification when attendance drops to 80%',
        'Calendar view to see attendance history by date',
      ],
      resources: [
        { label: 'Notification API (MDN)', url: 'https://developer.mozilla.org/en-US/docs/Web/API/Notifications_API' },
        { label: 'Date-fns Library', url: 'https://date-fns.org' },
      ],
      authorName: 'Rohit Deshmukh',
      authorGithub: 'https://github.com/rohitd-cse',
      devs: 156, isUserSubmitted: true, status: 'published',
      createdAt: new Date('2026-03-28'),
    },
    {
      id: 'comm-notes-app',
      category: 'web', difficulty: 'easy',
      title: 'Smart Notes App with Tags',
      desc: 'A minimal but powerful notes app with markdown support, tag-based organization, a full-text search, and auto-save — all stored locally without needing any server.',
      longDesc: 'I was tired of using Notepad for class notes. This notes app supports Markdown formatting, lets you tag notes (like #DSA, #OS, #DBMS), and has instant full-text search across all notes. Notes auto-save every few seconds and everything lives in localStorage so there\'s no account needed.',
      tech: ['javascript', 'html-css'],
      tags: ['Markdown', 'LocalStorage', 'Full-text Search', 'Tags'],
      skills: ['Markdown Parsing', 'Search Indexing', 'Auto-save', 'Tag Filtering'],
      requirements: [
        'Create, edit, and delete notes with a title and markdown body',
        'Live Markdown preview while typing',
        'Add multiple tags to each note for organization',
        'Filter notes by tag with one click',
        'Full-text search across all note titles and body content',
        'Auto-save every 3 seconds, with a "Saved" indicator',
      ],
      resources: [
        { label: 'Marked.js Markdown Parser', url: 'https://marked.js.org' },
        { label: 'MDN localStorage', url: 'https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage' },
      ],
      authorName: 'Ananya Iyer',
      authorGithub: 'https://github.com/ananyaiyer',
      devs: 71, isUserSubmitted: true, status: 'published',
      createdAt: new Date('2026-04-01'),
    },

    // ── Classic beginner projects from the internet ──────────────

    {
      id: 'comm-calculator',
      category: 'web', difficulty: 'easy',
      title: 'JavaScript Calculator',
      desc: 'Build a fully working calculator with a clean UI that supports addition, subtraction, multiplication, division, and keyboard input — a classic beginner project.',
      longDesc: 'One of the most popular first projects for web developers. Build a working calculator using HTML, CSS, and vanilla JavaScript. Supports chained operations, decimal numbers, keyboard shortcuts, and a clear/backspace button. Style it beautifully with a dark or glassmorphism design.',
      tech: ['javascript', 'html-css'],
      tags: ['HTML/CSS', 'Vanilla JS', 'DOM Events', 'UI Design'],
      skills: ['Event Listeners', 'DOM Manipulation', 'Math Logic', 'CSS Grid/Flexbox'],
      requirements: [
        'Display current input and running result on screen',
        'Buttons for digits 0–9, operators (+, −, ×, ÷), decimal, equals, and clear',
        'Support chained operations (e.g. 5 + 3 × 2)',
        'Handle division by zero with an error message',
        'Add keyboard support (numbers + operators from keyboard)',
        'Backspace button to delete last digit',
      ],
      resources: [
        { label: 'MDN: Event Listeners', url: 'https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener' },
        { label: 'CSS Grid Guide', url: 'https://css-tricks.com/snippets/css/complete-guide-grid' },
      ],
      authorName: 'Vikram Joshi',
      authorGithub: 'https://github.com/vikramj',
      devs: 8724, isUserSubmitted: true, status: 'published',
      createdAt: new Date('2026-01-10'),
    },

    {
      id: 'comm-todo-app',
      category: 'web', difficulty: 'easy',
      title: 'To-Do List App',
      desc: 'The go-to beginner project — build a task manager where you can add, complete, and delete tasks, with filters for All / Active / Completed and localStorage persistence.',
      longDesc: 'A well-executed To-Do list is one of the best ways to prove you understand CRUD operations, state management, and localStorage. This version includes filters, drag-to-reorder, task editing, due dates, and a clean minimal UI. Goes from "Hello World" to a genuinely useful app.',
      tech: ['javascript', 'html-css'],
      tags: ['LocalStorage', 'CRUD', 'Filters', 'HTML/CSS'],
      skills: ['CRUD Operations', 'Local Storage', 'Array Manipulation', 'Event Handling'],
      requirements: [
        'Add new tasks by typing and pressing Enter or clicking Add',
        'Mark tasks as complete by clicking a checkbox',
        'Delete tasks with a ✕ button (visible on hover)',
        'Filter tasks: All | Active | Completed',
        'Edit task text by double-clicking the task',
        'Persist tasks to localStorage so they survive a page refresh',
        'Show count of remaining active tasks',
      ],
      resources: [
        { label: 'MDN localStorage', url: 'https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage' },
        { label: 'TodoMVC Specs (reference)', url: 'https://github.com/tastejs/todomvc/blob/master/app-spec.md' },
      ],
      authorName: 'Meera Nair',
      authorGithub: 'https://github.com/meeranair-dev',
      devs: 12450, isUserSubmitted: true, status: 'published',
      createdAt: new Date('2026-01-15'),
    },

    {
      id: 'comm-tictactoe',
      category: 'game', difficulty: 'easy',
      title: 'Tic Tac Toe Game',
      desc: 'Build the classic 3×3 grid Tic Tac Toe game with two-player mode and an optional unbeatable AI opponent using the Minimax algorithm.',
      longDesc: 'A fantastic first game project. Build a 2-player Tic Tac Toe game with win detection, draw detection, and a scoreboard. Then extend it with an AI opponent that plays perfectly using the Minimax algorithm — making the game actually impossible to beat when on hard mode.',
      tech: ['javascript', 'html-css'],
      tags: ['Game Logic', 'Minimax AI', 'HTML/CSS', 'Vanilla JS'],
      skills: ['2D Game Logic', 'Win Detection Algorithm', 'Minimax AI', 'DOM Rendering'],
      requirements: [
        '3×3 grid where two players take turns clicking cells',
        'Detect and highlight winning combination (row, column, or diagonal)',
        'Detect draw when all cells are filled with no winner',
        'Display whose turn it is and announce the winner',
        'Restart button to reset the game',
        'Scoreboard tracking Player X and Player O wins',
        'Optional: AI opponent using the Minimax algorithm',
      ],
      resources: [
        { label: 'Minimax Algorithm Explained', url: 'https://www.geeksforgeeks.org/minimax-algorithm-in-game-theory-set-1-introduction' },
        { label: 'MDN: CSS Grid', url: 'https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_grid_layout' },
      ],
      authorName: 'Siddharth Rao',
      authorGithub: 'https://github.com/siddrao',
      devs: 6890, isUserSubmitted: true, status: 'published',
      createdAt: new Date('2026-01-20'),
    },

    {
      id: 'comm-quiz-trivia',
      category: 'web', difficulty: 'easy',
      title: 'Trivia Quiz App',
      desc: 'A 10-question trivia quiz fetching questions from the Open Trivia API — choose a category, difficulty, and see your score at the end with animated feedback.',
      longDesc: 'Build an interactive multiple-choice quiz app using the free Open Trivia Database API. Users select a category (Science, History, Sports, etc.) and difficulty, then answer 10 questions with a timer per question. Show instant right/wrong feedback, a progress bar, and a score summary at the end.',
      tech: ['javascript', 'html-css'],
      tags: ['Open Trivia API', 'Fetch', 'Animations', 'Timer'],
      skills: ['API Integration', 'Timer Logic', 'Score Tracking', 'DOM Updates'],
      requirements: [
        'Fetch 10 questions from Open Trivia DB API for the selected category and difficulty',
        'Display each question with 4 shuffled answer choices',
        'Highlight correct/incorrect answer with animation after selection',
        'Show a progress bar and question counter (e.g. 3/10)',
        'Countdown timer per question — auto-advance if time runs out',
        'Final score screen with percentage and a "Play Again" button',
      ],
      resources: [
        { label: 'Open Trivia Database API', url: 'https://opentdb.com/api_config.php' },
        { label: 'Fetch API (MDN)', url: 'https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch' },
      ],
      authorName: 'Pooja Kapoor',
      authorGithub: 'https://github.com/poojakapoor',
      devs: 4312, isUserSubmitted: true, status: 'published',
      createdAt: new Date('2026-01-28'),
    },

    {
      id: 'comm-password-gen',
      category: 'tool', difficulty: 'easy',
      title: 'Password Generator',
      desc: 'Generate strong, random passwords with options for length, uppercase, lowercase, numbers, and symbols — with a one-click copy and a strength indicator.',
      longDesc: 'A simple but genuinely useful tool. Users set the desired password length and toggle which character sets to include (uppercase, lowercase, digits, symbols). The app generates a secure random password, shows a visual strength meter, and copies it to clipboard in one click. Great for learning about randomness, string manipulation, and regex.',
      tech: ['javascript', 'html-css'],
      tags: ['Vanilla JS', 'Clipboard API', 'CSS', 'Randomization'],
      skills: ['String Manipulation', 'Randomization', 'Clipboard API', 'Regex'],
      requirements: [
        'Slider to set password length (8–128 characters)',
        'Checkboxes to include: uppercase, lowercase, numbers, special symbols',
        'Generate button creates a cryptographically random password',
        'Visual strength meter: Weak / Medium / Strong / Very Strong',
        'One-click copy to clipboard with confirmation feedback',
        'Re-generate button to get a new password without changing settings',
      ],
      resources: [
        { label: 'Crypto.getRandomValues (MDN)', url: 'https://developer.mozilla.org/en-US/docs/Web/API/Crypto/getRandomValues' },
        { label: 'Clipboard API (MDN)', url: 'https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API' },
      ],
      authorName: 'Rahul Bhatia',
      authorGithub: 'https://github.com/rahulbhatia-codes',
      devs: 5630, isUserSubmitted: true, status: 'published',
      createdAt: new Date('2026-02-05'),
    },

    {
      id: 'comm-stopwatch',
      category: 'web', difficulty: 'easy',
      title: 'Stopwatch & Timer App',
      desc: 'A precise stopwatch with lap recording, a countdown timer with audio alert, and keyboard shortcuts — all in a single clean UI.',
      longDesc: 'Build a dual-function time tool: a stopwatch that records lap times and a countdown timer that plays an alert when it reaches zero. Uses JavaScript\'s performance.now() for accuracy, CSS animations for the ticking effect, and the Web Audio API or an audio file for the alarm. A great project for learning timers and the event loop.',
      tech: ['javascript', 'html-css'],
      tags: ['setInterval', 'performance.now()', 'Web Audio API', 'CSS Animations'],
      skills: ['Timer Logic', 'Precision Timing', 'Audio API', 'State Management'],
      requirements: [
        'Stopwatch: Start, Pause, Reset, and Lap buttons',
        'Display hours, minutes, seconds, and centiseconds (HH:MM:SS.cs)',
        'Lap list showing each lap time and the split difference',
        'Countdown timer with user-settable hours/minutes/seconds',
        'Audio alarm when countdown reaches zero',
        'Keyboard shortcuts: Space = start/pause, L = lap, R = reset',
      ],
      resources: [
        { label: 'performance.now() (MDN)', url: 'https://developer.mozilla.org/en-US/docs/Web/API/Performance/now' },
        { label: 'Web Audio API', url: 'https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API' },
      ],
      authorName: 'Deepak Sharma',
      authorGithub: '',
      devs: 2190, isUserSubmitted: true, status: 'published',
      createdAt: new Date('2026-02-12'),
    },

    {
      id: 'comm-color-picker',
      category: 'tool', difficulty: 'easy',
      title: 'Color Palette Generator',
      desc: 'Generate beautiful, harmonious color palettes — lock colors you love and shuffle the rest. Copy hex codes with one click, just like Coolors.co.',
      longDesc: 'Build a Coolors-style color palette generator. Press spacebar to generate 5 new random colors. Lock individual colors you want to keep, then keep pressing spacebar to randomize the unlocked ones. Click any color to copy its hex code. Add accessibility contrast checking to show if text would be readable on each color.',
      tech: ['javascript', 'html-css'],
      tags: ['Color Theory', 'HSL', 'Clipboard API', 'CSS Variables'],
      skills: ['Color Math', 'CSS Variables', 'Clipboard API', 'Keyboard Events'],
      requirements: [
        'Display 5 large color swatches side by side',
        'Press spacebar or click Generate to randomize all unlocked colors',
        'Lock icon on each swatch — locked colors don\'t change on generate',
        'Click a color swatch to copy its hex code to clipboard',
        'Show hex, RGB, and HSL values for each color',
        'Accessibility badge: shows if white or black text has better contrast ratio',
      ],
      resources: [
        { label: 'Coolors.co (reference UI)', url: 'https://coolors.co' },
        { label: 'CSS Variables Guide', url: 'https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties' },
      ],
      authorName: 'Kavya Reddy',
      authorGithub: 'https://github.com/kavyareddy-ui',
      devs: 3780, isUserSubmitted: true, status: 'published',
      createdAt: new Date('2026-02-20'),
    },

    {
      id: 'comm-weather-app',
      category: 'web', difficulty: 'easy',
      title: 'Weather App (OpenWeatherMap)',
      desc: 'Search any city and instantly see current weather — temperature, feels like, humidity, wind, and a 5-day forecast — using the free OpenWeatherMap API.',
      longDesc: 'One of the most popular beginner API projects. Users type a city name or allow geolocation, and the app fetches current weather and a 5-day forecast from the OpenWeatherMap free API. Display animated weather icons that change based on the condition (sunny, cloudy, rainy). Add a day/night background that changes based on local time.',
      tech: ['javascript', 'html-css'],
      tags: ['OpenWeather API', 'Geolocation', 'Fetch', 'CSS Animations'],
      skills: ['API Integration', 'Async/Await', 'Geolocation API', 'Data Display'],
      requirements: [
        'Search bar to look up any city by name',
        'Display: city name, country, temperature (°C / °F toggle), feels like, humidity, wind speed',
        'Animated weather icon matching the current condition',
        'Show 5-day forecast with daily high/low and icon',
        'Auto-detect user location via Geolocation API on first load',
        'Dynamic background/theme that changes between day and night',
      ],
      resources: [
        { label: 'OpenWeatherMap Free API', url: 'https://openweathermap.org/api' },
        { label: 'Geolocation API (MDN)', url: 'https://developer.mozilla.org/en-US/docs/Web/API/Geolocation_API' },
      ],
      authorName: 'Aditya Kulkarni',
      authorGithub: 'https://github.com/adityak-codes',
      devs: 9120, isUserSubmitted: true, status: 'published',
      createdAt: new Date('2026-02-28'),
    },

    {
      id: 'comm-expense-splitter',
      category: 'web', difficulty: 'medium',
      title: 'Group Expense Splitter',
      desc: 'Split bills fairly among friends — add group members, log shared expenses, and the app calculates exactly who owes who and how much.',
      longDesc: 'The classic problem: you go on a trip with friends and need to split the bill. This app lets you add group members, log shared expenses (who paid, who was involved, how much), and then calculates the minimum number of transactions needed to settle all debts. A great real-world logic problem disguised as a simple app.',
      tech: ['javascript', 'html-css'],
      tags: ['Debt Settlement', 'Algorithm', 'LocalStorage', 'Forms'],
      skills: ['Debt Minimization Algorithm', 'CRUD', 'Complex State', 'UI Logic'],
      requirements: [
        'Add group members with names and optional avatars',
        'Log an expense: payer, amount, title, and who to split between',
        'Support equal split or custom amounts per person',
        'Show each person\'s total paid and total owed',
        'Calculate and display the minimum transactions to settle all debts (e.g. A pays B ₹250)',
        'Persist group and expenses to localStorage',
      ],
      resources: [
        { label: 'Debt Simplification Algorithm', url: 'https://www.geeksforgeeks.org/minimize-cash-flow-among-given-set-friends-borrowed-money' },
        { label: 'MDN localStorage', url: 'https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage' },
      ],
      authorName: 'Tanvi Patil',
      authorGithub: 'https://github.com/tanvipatil',
      devs: 1870, isUserSubmitted: true, status: 'published',
      createdAt: new Date('2026-03-05'),
    },

    {
      id: 'comm-typing-speed',
      category: 'tool', difficulty: 'medium',
      title: 'Typing Speed Test',
      desc: 'Measure your typing speed in WPM and accuracy. Shows a random passage, highlights errors in real time, and gives a detailed performance breakdown at the end.',
      longDesc: 'Build a typing speed test app inspired by MonkeyType and Keybr. Display a random paragraph and as the user types, highlight each character green (correct) or red (incorrect). Track elapsed time and calculate Words Per Minute (WPM) and accuracy percentage. Show a results breakdown by character accuracy and personal best tracking.',
      tech: ['javascript', 'html-css'],
      tags: ['WPM Calculation', 'Real-time Highlight', 'LocalStorage', 'Timer'],
      skills: ['String Comparison', 'Real-time Input', 'Timer Logic', 'Statistics'],
      requirements: [
        'Display a randomly selected passage to type',
        'Highlight characters green (correct) or red (wrong) as user types',
        'Live WPM counter updated every second',
        'Accuracy percentage calculated after each word',
        'Auto-stop when the passage is complete, show final stats',
        'Save personal best WPM and accuracy to localStorage',
        'Difficulty setting: Easy (short words) / Hard (longer technical words)',
      ],
      resources: [
        { label: 'MonkeyType (reference app)', url: 'https://monkeytype.com' },
        { label: 'MDN: Input Events', url: 'https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/input_event' },
      ],
      authorName: 'Nikhil Verma',
      authorGithub: 'https://github.com/nikhilverma-dev',
      devs: 3250, isUserSubmitted: true, status: 'published',
      createdAt: new Date('2026-03-10'),
    },
  ];

  // ── Helper utilities available globally ──
  window.LF = {
    getAll: () => window.LF_PROJECTS,
    getById: (id) => window.LF_PROJECTS.find(p => p.id === id),
    getFeatured: () => window.LF_PROJECTS.filter(p => p.featured),
    getCommunityDemo: () => window.LF_COMMUNITY_DEMO,
    catLabel: (c) => ({ web:'🌐 Web', mobile:'📱 Mobile', tool:'🛠️ Tools', ai:'🤖 AI / ML', game:'🎮 Games' }[c] || c),
    diffColor: (d) => ({ easy:'badge-easy', medium:'badge-medium', hard:'badge-hard' }[d] || ''),
    formatNum: (n) => n >= 1000 ? (n / 1000).toFixed(1) + 'k' : String(n),
    totalDevs: () => window.LF_PROJECTS.reduce((s, p) => s + (p.devs || 0), 0),
  };
})();
